repos:
- repo: local
  hooks:
    - id: test
      name: test
      description: Run all tests.
      entry: task test
      language: system
      always_run: true
      fail_fast: true
      pass_filenames: false
      stages: [push]
