default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # fix for https://github.com/fastlane/fastlane/issues/29528
    ENV["PATH"] = "#{File.expand_path("../scripts", __dir__)}:#{ENV["PATH"]}"

    increment_build_number(xcodeproj: "Habits.xcodeproj")

    build_app(scheme: "habits")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    commit_version_bump
  end
end

# TODO:
# add lane to handle certificates (readonly locally)
