default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Habits.xcodeproj")
    build_app(scheme: "habits")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

# TODO:
# add lane to handle certificates (readonly locally)
